import { Transaction, BudgetGoal } from '../types';

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    date: '2026-08-28',
    description: 'Salário Mensal Instituto',
    amount: 6500.0,
    type: 'RECEITA',
    category: 'Salário & Renda',
    paymentMethod: 'Transferência',
    status: 'Pago',
    notes: 'Pagamento referente ao mês',
    source: 'manual',
    syncedToSheets: true,
    createdAt: '2026-08-28T09:00:00.000Z',
  },
  {
    id: 'tx-2',
    date: '2026-08-28',
    description: 'Supermercado Pão de Açúcar',
    amount: 384.5,
    type: 'DESPESA',
    category: 'Supermercado',
    paymentMethod: 'Cartão de Crédito',
    status: 'Pago',
    notes: 'Compras de mantimentos para a semana',
    source: 'image',
    syncedToSheets: true,
    createdAt: '2026-08-28T17:32:00.000Z',
  },
  {
    id: 'tx-3',
    date: '2026-08-29',
    description: 'Almoço Restaurante Bistrô',
    amount: 52.9,
    type: 'DESPESA',
    category: 'Alimentação',
    paymentMethod: 'PIX',
    status: 'Pago',
    notes: 'Almoço executivo',
    source: 'audio',
    syncedToSheets: true,
    createdAt: '2026-08-29T12:45:00.000Z',
  },
  {
    id: 'tx-4',
    date: '2026-08-29',
    description: 'Uber para Reunião de Trabalho',
    amount: 28.4,
    type: 'DESPESA',
    category: 'Transporte',
    paymentMethod: 'Cartão de Crédito',
    status: 'Pago',
    notes: 'Deslocamento centro',
    source: 'text',
    syncedToSheets: true,
    createdAt: '2026-08-29T14:10:00.000Z',
  },
  {
    id: 'tx-5',
    date: '2026-08-29',
    description: 'Freelance Design de Interface',
    amount: 1400.0,
    type: 'RECEITA',
    category: 'Freelance & Serviços',
    paymentMethod: 'PIX',
    status: 'Pago',
    notes: 'Entrega de protótipo Figma',
    source: 'text',
    syncedToSheets: true,
    createdAt: '2026-08-29T18:20:00.000Z',
  },
  {
    id: 'tx-6',
    date: '2026-08-30',
    description: 'Farmácia Droga Raia',
    amount: 89.2,
    type: 'DESPESA',
    category: 'Saúde & Farmácia',
    paymentMethod: 'Cartão de Débito',
    status: 'Pago',
    notes: 'Vitaminas e analgésico',
    source: 'image',
    syncedToSheets: true,
    createdAt: '2026-08-30T10:15:00.000Z',
  },
  {
    id: 'tx-7',
    date: '2026-08-30',
    description: 'Assinatura Spotify + Netflix',
    amount: 79.8,
    type: 'DESPESA',
    category: 'Assinaturas & Tech',
    paymentMethod: 'Cartão de Crédito',
    status: 'Pago',
    notes: 'Débito automático mensal',
    source: 'manual',
    syncedToSheets: true,
    createdAt: '2026-08-30T08:00:00.000Z',
  },
];

export const INITIAL_BUDGET_GOALS: BudgetGoal[] = [
  { category: 'Alimentação', limit: 800 },
  { category: 'Supermercado', limit: 1200 },
  { category: 'Transporte', limit: 400 },
  { category: 'Lazer & Viagens', limit: 600 },
  { category: 'Moradia & Contas', limit: 2000 },
  { category: 'Saúde & Farmácia', limit: 300 },
  { category: 'Compras & Vestuário', limit: 500 },
];
